### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by wfma** [mrdwab/SOfun#7]
Hi, I tried to install the SOfun package but ran into this problem.

ERROR: dependency ‘overflow’ is not available for package ‘SOfun’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/SOfun’

I have R version 3.3.1

**Comment by DeLaRiva** [comment]
I've the same issue:

> ERROR: dependencies ‘XML’, ‘overflow’ are not available for package ‘SOfun’
> * removing ‘/home/ben/R/x86_64-pc-linux-gnu-library/3.4/SOfun’

**Comment by mrdwab** [comment]
@DeLaRiva , @wfma , I'll check whether overflow needs to be imported or not. You can install overflow from https://github.com/mrdwab/overflow-mrdwab

**Comment by mrdwab** [comment]
Closed with https://github.com/mrdwab/SOfun/commit/30cb2d5099560b810925f71a8bb9dbcf92cec0cb.
